lsst/sdm_schemas

.github/workflows/build.yaml
tap-schema/Dockerfile
tap-schema/build
tap-schema/build-all
tap-schema/sql/0000_tap_schema11.sql
tap-schema/sql/0004_tap_schema.permissions.sql
tap-schema/sql/1003_uws_tap_schema.sql

Add ci plumbing and move the docker image here from the lsst-tap-schema repo

[DM-30753] TAP SCHEMA publishing

---

yml/dp02_dc2.yaml

PR to reflect the additional GAaP columns added to the object table.
I have not included the changes to be made in DM-31825

DM-31912: Add extra GAaP columns to sdm_schema

---

datalink/dp01_object_cone_search.xml
datalink/dp01_position_cone_search.xml
datalink/dp01_truth_match_cone_search.xml

By passing them in here, it still works and passes it through,
but doesn't show up in the form.

[DM-32513] Hide some parameters for the redirect

---

browser/dp02.md
yml/dp02.yaml

Adds yaml for schema corresponding to DP0.2 catalog test slice as ingested on IDF `int` Qserv instance.  Adds blurb to publish in schema browser.

Add preliminary DP0.2 schema

---

tap-schema/build-all
yml/dp02_obscore.yaml
yml/ivoa/ObsCore-v1.1-descriptions.csv
yml/ivoa/ObsCore-v1.1-mandatory.csv
yml/ivoa/ObsCore-v1.1-optional.csv
yml/ivoa/README.md
yml/ivoa/make_obscore_nominal.py
yml/ivoa/obscore_nominal.yaml

**DRAFT** PR so far.
Provided reference information on the IVOA ObsCore standard in machine-readable form.

DM-34814: Provide Felis for DP0.2 ObsTAP table

---

yml/dp02_dc2.yaml
yml/hsc.yaml
yml/imsim.yaml

I also noticed that there were modifications made to dp02_dc2.yaml that weren't propagated to imsim.yaml. 
I propagated those over first. 
main/dp02_dc2.yaml should == v23.0.x/imsim.yaml

DM-31950: Add descriptions and units to imsim and hsc schemas

---

yml/dp02_obscore.yaml

- These need UCD's, utypes, and/or units as appropriate?

Add new lsst-specific ObsCore columns for DP0.2

---

yml/dp02_dc2.yaml

This picks up where PR#63 left off...

Add `CoaddPatches` ("tract/patch") table for DP0.2

---

datalink/datalink-manifest.json
datalink/obscore_links.xml

[DM-35459] Fix capitalization issues

---

datalink/obscore_links.xml

pyvo is unhappy there's no inputParams group, let's see if an empty
one will work.

[DM-35459] Try to add an empty inputParams

---

datalink/datalink-manifest.json
datalink/dp02_object_to_fs_timeseries.xml

This enables an initial test of the new /api/datalink/timeseries service.
Related to DM-35254 and https://github.com/lsst-sqre/datalinker/pull/52

DM-36077: Add Object-to-ForcedSource time series query DataLink

---

tap-schema/build-all

Added line to build idf dev schema using idf int schema values.  Allows testing against int data from dev

Added idf dev build line to build tap from int

---

tap-schema/build-all
yml/live_obscore.yaml

This technically isn't the standard, but apparantly we're not going to make it the standard name, at least not for a while.

[DM-38110] Make a temporary oga.Obscore tap_schema db

---

.github/workflows/felislint.yaml
tap-schema/felis-validate

Validates all .yaml files in the yml directory,
but not subdirectories.

[DM-39735] Add a script to use felis to validate

---

yml/imsim.yaml

Change dipoleNdata from double to BIGINT

DM-37911-hotfix: Change dipoleNdata from double to BIGINT

---

.github/workflows/validator.yaml

This modifies the validator workflow so that it is triggered manually rather than automatically.

DM-41288: Change validator github workflow to on-demand

---

.github/workflows/validator.yaml

This allows the validation workflow to be manually dispatched using on main or a selected branch.

DM-41288: Remove conditional on running the validation job

---

yml/dp02_dc2.yaml

Implements various relatively minor updates to the DP02 schema YAML file. All edits are intended to only affect the "description" field.

PREOPS-4974: Implement minor corrections to column descriptions in DP0.2 schema

---

yml/dp02_dc2.yaml

Remove redundant mysql datatype

---

.github/workflows/validate.yaml

Also updated the validation workflow so that it can be triggered manually.

DM-44058: Add redundant datatype checks to validation workflow

---

browser/cdb_latiss.md
browser/cdb_lsstcomcamsim.md
yml/cdb_latiss.yaml
yml/cdb_lsstcomcam.yaml
yml/cdb_lsstcomcamsim.yaml

Includes quicklook-sourced columns.

DM-44489: Add visit1 and ccdvisit1 tables.

---

yml/hsc.yaml
yml/imsim.yaml

DM-46933: Remove references to STREAK mask

---

python/lsst/sdm_schemas/schemas/cdb_lsstcomcam.yaml

I've incremented the minor version to 3.5.0 in preparation for the deployment of some new columns and documentation.

DM-47308: Increment minor version of cdb_lsstcomcam and add electron UCDs

---

python/lsst/sdm_schemas/schemas/apdb.yaml
python/lsst/sdm_schemas/schemas/imsim.yaml

This reverts commit 46b25b99f64e8daa8c342490a92a18e54a6fc9fe.

DM-48009: Revert #279 "Add attempted dipole classification of object to APDB"

---

.gitignore

DM-48321: Ignore build files

---

python/lsst/sdm_schemas/schemas/apdb.yaml

DM-44098: Add nDiaSources to DiaObjectLast

---

tap-schema/build

Use new CLI command in tap-schema build

---

.github/workflows/test_mysql.yaml
.github/workflows/test_postgresql.yaml
.github/workflows/test_sqlite.yaml
scripts/test/load-tap-schema.sh

This patches the tests to use new TAP_SCHEMA commands.

Use new TAP_SCHEMA commands in database test cases

---

.github/workflows/test_sqlite.yaml
scripts/test/load-tap-schema.sh

Cleanup TAP_SCHEMA database tests

---

pyproject.toml
requirements.txt

Change github links in requirements from http to https

---

python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

DM-49274: Separate NO_DATA from EDGE pixel flag in the HSC schema

---

python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

DM-49074: Cast table columns to single precision in SDM-standardization functors

---

CONTRIBUTING.md
docs/CDB.md

DM-48177: Add ConsDB-specific documentation.

---

python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

DM-49727: Add epoch columns to Object table

---

python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

DM-49710: Add sky-coordinate moments to imsim and HSC.

---

python/lsst/sdm_schemas/schemas/imsim.yaml

DM-49729: Propagate noData flags into ForcedSourceTables - Backport v29

---

.github/pull_request_template.md
.gitignore
browser/CHANGES.md
browser/_includes/_schema_list.html
browser/_layouts/changes.html
browser/_layouts/schema.html
docs/changes/DM-49074.sci.md
docs/changes/DM-49274.sci.md
docs/changes/DM-49710.sci.md
docs/changes/DM-49727.sci.md
docs/changes/DM-49729.sci.md
docs/changes/README.md
pyproject.toml

DM-49711: Add towncrier support

---

python/lsst/sdm_schemas/schemas/hsc.yaml
python/lsst/sdm_schemas/schemas/imsim.yaml

DM-49074: Cast table columns to single precision in SDM-standardization functors -- Backport v29

---

.github/actions/setup-test-environment/action.yaml
.github/pull_request_template.md
.github/workflows/build.yaml
docs/changes/DM-49962.misc.md
pyproject.toml
requirements.txt
ups/sdm_schemas.table

DM-49962: Remove SDM Tools dependency

---

python/lsst/sdm_schemas/schemas/hsc.yaml
python/lsst/sdm_schemas/schemas/imsim.yaml

DM-49727-v29: Add epoch columns to Object table

---

docs/changes/DM-49767.sci.md
tap-schema/sql/0000_tap_schema11.sql

Revert "DM-49767: Change id to column_id in tap_schema columns"

---

browser/cdb_latiss.md
browser/cdb_lsstcam.md
browser/cdb_lsstcomcam.md
browser/cdb_lsstcomcamsim.md
browser/cdb_startrackerfast.md
browser/cdb_startrackernarrow.md
browser/cdb_startrackerwide.md
docs/changes/DM-50521.misc.md

DM-50521: Add cdb_lsstcam to schema browser

---

browser/_layouts/schema.html
docs/changes/DM-46240.misc.md

DM-46240: Remove dependence on '@id' field from the schema browser

---

docs/changes/DM-47965.cdb.md
python/lsst/sdm/schemas/cdb_latiss.yaml
python/lsst/sdm/schemas/cdb_lsstcam.yaml
python/lsst/sdm/schemas/cdb_lsstcomcam.yaml
python/lsst/sdm/schemas/cdb_lsstcomcamsim.yaml

Add scheduler_note column to consdb exposure tables.

---

docs/changes/DM-50914.misc.md

Add news fragment that was missing from #343 

DM-50914: Add news fragment

---

docs/changes/DM-51064.dr.md
python/lsst/sdm/schemas/dp03_10yr.yaml
python/lsst/sdm/schemas/dp03_1yr.yaml

DM-51064: Correct ssObjectReassocTime datatype to match DP0.3 DB

---

docs/changes/DM-51051.cdb.md
python/lsst/sdm/schemas/cdb_latiss.yaml
python/lsst/sdm/schemas/cdb_lsstcam.yaml
python/lsst/sdm/schemas/cdb_lsstcomcam.yaml
python/lsst/sdm/schemas/cdb_lsstcomcamsim.yaml

**Schema version number increment for cdb_lsstcam will have to be reconciled with the DM-51220 PR also in progress.**

Add column can_see_sky for cdb.

---

docs/changes/DM-51220.cdb.md
python/lsst/sdm/schemas/cdb_lsstcam.yaml

Add zernikes to cdb_lsstcam.ccdvisit1_quicklook

---

docs/changes/DM-51410.dr.md
python/lsst/sdm/schemas/dp1.yaml

DM-51410: Remove '@id' fields from dp1.yaml

---

python/lsst/sdm/schemas/dp02_dc2.yaml

DM-51478: Move DP0.2 ObsCore table above Visit in presentation

---

docs/changes/DM-51507.dr.md
python/lsst/sdm/schemas/ivoa_obscore.yaml
tap-schema/build-all

Retaining DP0.2 version and controlling deployment via build-all file

DM-51507: Add new static-ObsCore file for DP1

---

docs/changes/DM-51560.dr.md
python/lsst/sdm/schemas/dp1.yaml

DM-51560: Add CoaddPatches table

---

python/lsst/sdm/schemas/dp1.yaml

DM-51440: Add missing units to columns in DiaObject table

---

browser/_layouts/schema.html

Fix issue in sorting tables on `tap:table_index`

---

.github/workflows/check_band_columns.yaml
docs/changes/DM-51417.dr.md
python/lsst/sdm/schemas/dp1.yaml

DM-51417-jbosch: add descriptions and tap:principal to Object columns

---

datalink/datalink-manifest.json
datalink/dp1_diaobject_to_diafs_timeseries.xml
datalink/dp1_diaobject_to_dias_timeseries.xml
datalink/dp1_object_to_fs_timeseries.xml
docs/changes/DM-51416.dr.md

DM-51416: Add basic DataLink support for DP1

---

docs/changes/DM-51552.dr.md
python/lsst/sdm/schemas/dp1.yaml

DM-51552: Revert `tickets/DM-51552`

---

docs/changes/DM-51764.cdb.md
python/lsst/sdm/schemas/cdb_lsstcam.yaml

DM-51764: Add hexapod motion columns and fix missing column

---

docs/changes/DM-50988.ap.md
docs/changes/DM-50988.sci.md
python/lsst/sdm/schemas/apdb.yaml
python/lsst/sdm/schemas/imsim.yaml

This PR adds one column to DiaSource and updates a few descriptions as a bonus.
~~I don't think the changes are substantial enough to warrant versioning, but if that is incorrect, please let me know.~~

DM-50988: Flag DIASources consistent with glints from rotating space junk

---

docs/changes/DM-51864.ap.md
python/lsst/sdm/schemas/apdb.yaml

Update to match DP1 (plus a and M)

---

docs/changes/DM-51993.ap.md
python/lsst/sdm/schemas/apdb.yaml

Updated SSSource velocity units

---

docs/changes/DM-49714.sci.md
python/lsst/sdm/schemas/imsim.yaml

DM-49714: Add trailFluxErr to imsim yaml

---

docs/changes/DM-50837.ap.md
docs/changes/DM-50837.sci.md
python/lsst/sdm/schemas/apdb.yaml
python/lsst/sdm/schemas/imsim.yaml

DM-50837: Schema Update for First Alerts

---

docs/changes/DM-52462.sci.md
python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

Add exponential columns to HSC/imsim schemas
