yml/dp01_dc2.yaml

We will have to review UTF-8-cleanliness of our whole metadata chain in the future.

Remove a non-ASCII character and fix a typo.

---

yml/hsc.yaml
yml/hsc_gen2.yaml

This PR adds the appropriate GAaP fields to SDM schemas in order to pass the build with `ci_hsc`.

DM-30858: Add GAaP fields to obs_subaru package

---

tap-schema/build-all
yml/wise_01.yml

The NCSA instances use Qserv-small.  This means:
* The newer "wise_01" database is used, superseding "wise_00".
* The DP0.1 tables are not available.
* No SDSS tables are available any longer.

DM-31093: Updated TAP_SCHEMA for NCSA to be closer to Qserv reality

---

yml/dp01_dc2.yaml

Also assigned `column_index` values to selected columns (ID, ra, dec) to move them to the top in the Portal.

DM-31077: Assign "principal" values to a subset of DP0.1 columns

---

datalink/dp01_object_cone_search.xml

Main purpose of this change is to add the units and UCD to the "radius" parameter; the rest are small cleanups.

Add units and UCDs; revise descriptions

---

yml/hsc.yaml
yml/hsc_gen2.yaml
yml/imsim.yaml

The single frame extendedness column is used for QA.
Therefore, the fluxes from which it is computed
(gaussian and psf) will also be used for QA. If a column is
needed for QA then it will also be needed during analysis.

DM-32666: Add gaussianFlux to Source Table

---

CNAME
_config.yml
tap-schema/requirements.txt

* Add CNAME file now required to publish github pages (schema browser) from custom domain (dm.lsst.org).
* Add config directors to have browser skip the ups/ and datalink/ subdirectories.

DM-32731: schema browser fixes

---

CNAME

not desired, after all -- TLD is configured further up, as CNAME for lsst.github.io

Remove github pages CNAME for schema browser

---

yml/dp02_dc2.yaml

Unfortunately, database name in back-end Qserv for the DP02 preview test slice is not the desired "harmonious" name for DP02 catalogs in tap_schema, and I am not aware that these names can be set independently.  Setting to the name as ingested for now.  We will correct this on the next test ingest.

Match name of dp02 preview slice to Qserv

---

yml/apdb.yaml
yml/baselineSchema.yaml

This schema is the same as currently defined in existing YAML files in
dax_apdb and ap_association packages. Some columns have their `nullable`
attributes corrected to reflect the design. There are differences w.r.t.
baselineSchema, in particular APDB schema does not include few columns
that were added recently to baseline schema - `nearbyExtObj[1-3]`,
`nearbyLowzGal`, and corresponding separation columns. And there are few
columns in APDB that do not exist in baseline schema for DIA tables.

DM-34480: Add APDB schema definition based on felis

---

yml/dp02_dc2.yaml
yml/dp02_dc2_preops-863.yaml

Workaround for a Firefly bug but legitimate in its own right.

DM-35221: Mark single-character columns as variable-length strings in VOTable output

---

yml/dp02_dc2.yaml

Commenting out `MatchesTruth` and `MatchesObject` table descriptions, to reduce confusion since these will not be initially offered with DP0.2.  We will restore these descriptions once the table formats are finalized and tables are populated on the release servers.

Elide `MatchesTruth`,`MatchesObject` from DP0.2

---

browser/dp02.md
tap-schema/build-all
yml/dp02_dc2.yaml

- Add schema description text to felis and browser blurb
- Remove "(preliminary)" from browser blurb
- Add tap table ordering indices
- Promote DP0.2 schema to top billing in browser

Minor cleanups for DP0.2 schema

---

.github/workflows/build.yaml
tap-schema/set_schema_index

As of earlier today, Felis requires Python 3.10.  Update version used in build GHA by adding actions/setup-python step.

Update Python for build GHA

---

browser/_layouts/schema.html
browser/dp01.md
browser/dp02.md

Make some minor tweaks to the schema browser, motivated by DP0.2:
- Render table names in navbar based on schema `name` attribute (not `id`)
- Render blurb text from top-level schema `description` attribute if present
- Render units first from `ivoa:unit`, if present, falling back to `fits:tunit`

DM-35333: Minor fixes to schema browser

---

yml/baselineSchema.yaml
yml/sdss_stripe82_01.yml

This PR fixes a few small issues with the felis description files.
* `mysql:datatype` should be `INTEGER` instead of `INT` - this is just because sqlalchemy doesn't recognize the `INT` alias as a data type for mysql
* Some `@id` 's had some copy/paste errors
* Constraint types were missing. The constraint types could probably be inferred by their attributes but currently they are required for constraints.

Felis Cleanups

---

yml/dp02_dc2.yaml
yml/imsim.yaml

and bring  the non-band specific columns: 
diaObjectId, ra, decl, radecTai, and nDiaSources to top of column list.

DM-35174: Add descriptions to diaObject columns

---

yml/dp02_obscore.yaml

This PR corrects an error in the `std` designation for the `lsst_patch` attribute, and adds descriptions and UCDs for all the `lsst_*` attributes.

DM-35956: Correct error in ObsTAP metadata; supply missing metadata

---

datalink/dp02_object_to_fs_timeseries.xml

Because of a bug in Firefly 2022.2.2, service descriptors without a `standardID` trigger an exception.  To work around this, we include a temporary, internal `standardID` for the timeseries service.  It is not yet clear whether this is a good
idea to do in the long term.  DataLink 1.0 suggests that this is not OK, but realistically a standardID without the `ivo:` prefix seems like a good hint that it should be ignored.
I will return to this question in the future.

DM-36077: (part 2) Add an internal standardID as a workaround

---

yml/dp02_dc2.yaml

Follows recent annotation of ForcedSourceOnDiaObject at the time
of its restoration to DP0.2.
Clarify description of ccdVisitId for forced photometry tables.

DM-36082: Full annotation of ForcedSource: UCDs, column_index, principal

---

.github/workflows/build.yaml
.gitignore
README.md
datalink/build
datalink/build_column_lists.py
datalink/build_datalink_metadata.py
datalink/columns-minimal.yaml

To support datalinker endpoints that return selected lists of
columns from tables, we want to communicate to datalinker the
list of columns with specific Felis tags in various tables.
Add a Python script that generates a YAML file of columns tagged
with tap:principal, and create a zip file as a release artifact
that can be downloaded by datalinker when it starts.
Add a placeholder columns-minimal.yaml file that will be maintained
by hand for now.

[DM-35254] Add generation of column lists for datalinker

---

yml/apdb.yaml

Adds `length` attribute to all `timestamp` columns. Fixes mysql INTEGER type spelling. Quote `value` attribute which has to be string.

DM-36216: Fix few issues in APDB felis schema

---

.github/workflows/build.yaml
.github/workflows/felislint.yaml
tap-schema/validator

Check for some basic things, like if the table indexes are there and unique, that each column has a description, and that there are principal columns for each table.

[DM-24785] Felis yaml validator

---

yml/dp01_dc2.yaml
yml/dp02_obscore.yaml

Also correct some of the existing validation errors.

DM-38507: Supply schema for the new ObsCore columns

---

yml/dp03.yaml

Only reflects preliminary data file schema with no modifications.

DM-38831: Initial DP0.3 schema

---

tap-schema/build-all
yml/dp03.yaml

Split DP0.3/SSO/Postgres away from DP0.2/Qserv in TAP_SCHEMA builds, as these are on entirely distinct database servers.
Refine DP0.3 schema description to be stylistically a bit more like DP0.2.

DM-39309: Split DP0.3/SSO/Postgres away from DP0.2/Qserv

---

tap-schema/build-all

This is actually put in by the build part of the script silently

[DM-39343] Remove tap-schema prefix

---

browser/dp03.md

Omitting the 1-year schema since it is identical.

Add DP0.3 to the schema browser.

---

yml/apdb.yaml
yml/imsim.yaml

Implement dipoleNdata column in the apdb

DM-37911: implement dipoleNdata

---

yml/dp02_obscore.yaml
yml/oga_live_obscore.yaml

So there's this special datatype called clob.  You can look up the full reference here:
https://www.ivoa.net/documents/ADQL/20180112/PR-ADQL-2.1-20180112.html
Section 3.4.2
So it's just like a character type or a unicode type, but the special part with a clob is that the value is generated by the server, not just stored in a database.  This is a bit complicated but it makes sense after thinking about it for a minute.  Since the TAP service is going to be making changes to the access_url column stored in the database, it means you can't use an ADQL query through the TAP service on that column.  This is because the ADQL (SQL) query is run before the TAP server modifies the return / generates the field, then any kind of restrictions (like a LIKE) will be 'ignored'.  So by setting to this …

[DM-40764] Set access_url to xtype clob

---

yml/imsim.yaml

A new flag has been added to imsim.yaml, ext_trailedSources_Naive_flag_edge, for use in trailedsource filtering.

DM-40412: Update imsim yaml to include trailedSource edge flag

---

yml/dp02_dc2.yaml

This demonstrates working foreign key constraints in felis that are loaded into the TAP_SCHEMA table.
I checked that the `felis load-tap` command results in the correct data for the constraint being loaded into the TAP_SCHEMA database in MySQL.

DM-41251: Add foreign key constraint from ForcedSource to Object

---

yml/hsc.yaml
yml/imsim.yaml

This PR adds streak and streakCenter pixel flags to the appropriate schemas.
Now without a branch name typo!

DM-32769: Implement streak detection and masking in single frame processing

---

yml/dp02_dc2.yaml

This is the first group of keys; a second group will follow.

DM-41652: Add all intra-DP0.2 single-attribute foreign keys

---

yml/dp02_dc2.yaml
yml/imsim.yaml

This replaces a few usages of "double" with "DOUBLE" that were causing DDL generation errors.

DM-41355: Fix mysql datatype errors in SDM schemas

---

yml/apdb.yaml
yml/dp01_dc2.yaml
yml/dp02_dc2.yaml
yml/hsc.yaml
yml/imsim.yaml

This fixes some trivial misspellings in schema files found using Pydantic validation.

DM-41921: Fix misspelled attribute names in schemas

---

.github/workflows/validator.yaml

This adds a space after a comment to fix a warning in the yaml linting that was appearing in the Github Workflow log.

Fix warning message in yaml linting

---

yml/dp01_dc2.yaml

The unit "pixels" is changed to "pixel". The unit "asec^2" is changed to "arcsec^2". The unit "asec" is changed to "arcsec". The new values were checked for validity using the astropy Unit class.

DM-41923: Fix unit errors in DP0.1 schema

---

datalink/dp02_diaobject_to_dias_timeseries.xml

In DiaSource, the band_column is not named 'band' as in the other three source-like tables; it is called 'filterName'. This is a temporary patch for DP0.2. The column names will be made consistent in the next major revision of the DRP data model.

DM-42069: Fix to override the band_column for DiaSource time series query

---

yml/imsim.yaml
yml/obsloctap.yaml

This fixes a single typo in obsloctap and three UCDs not following standard syntax in imsim.
The imsim fixes were:
- pos.eq.decErr -> stat.error;pos.eq.dec
- pos.eq.raErr -> stat.error;pos.eq.ra
- pos.eq.ra_dec_Cov -> stat.covariance;pos.eq.ra;pos.eq.dec
These were checked for correctness with the `ucd.parse_ucd` function in astropy via Pydantic command line validation.

DM-42003: Fix UCD errors in SDM schemas

---

yml/dp02_dc2.yaml

This fixes two reoccurring lint errors showing up in the log of the Github workflow for PRs.

DM-42167: Fix errors reported by yamllint due to incorrectly indented comments

---

yml/dp01_dc2.yaml

The string "Source''s" was change to remove the improper usage of two single quotes. The description fields containing this string were enclosed in double quotes so that the single quotes did not need to be escaped.
The string "''regauassianization" was changed to use escaped double quotes instead of double single quotes.

DM-42247: Fix issues with single quote usage in DP0.1 schema

---

yml/apdb.yaml

Change several fields from non-nullable to nullable

DM-24283: Update nullable fields

---

.github/workflows/build.yaml
.github/workflows/validate.yaml

The name of the package was changed to "lsst-felis" so the egg name in the URL needed to be updated.

DM-41289: Fix egg name in pip URL

---

yml/apdb.yaml

This also adds version number to APDB schema and "advances" it to 0.1.1, all schema versions before metadata are considered 0.1.0.

DM-41029: Add metadata table to APDB schema

---

.github/workflows/build.yaml
.github/workflows/validate.yaml

Felis is now available on PyPI as "lsst-felis" so change to using this instead of the Github URL.

DM-42404: Install felis with pip using its package name instead of the Github URL

---

yml/dp03_10yr.yaml
yml/dp03_1yr.yaml

This change was made on a branch in August 2023 and lost in the shuffle.

DM-42781: Put the different time spans of the DP0.3 schema descriptions up front

---

doc/dp02_dc2.mmd
yml/README.md
yml/dp02_dc2.yaml

Includes:
- DM-42772: Add foreign-key links for MatchesTruth table
- DM-42785: Improve annotation of times and durations
- Better annotation of the attributes used in foreign-key relationships

DM-41652: Part 2 of adding single-attribute foreign keys to DP0.2

---

yml/dp03_10yr.yaml
yml/dp03_1yr.yaml

Missing TAP table indices were added and some missing column descriptions were filled in. 
It should be discussed further which columns should be flagged as TAP principal. I did not add these for now.

DM-43011: Set TAP table indices and supply missing column descriptions for DP0.3 schemas

---

yml/apdb.yaml

Similar to [DM-43011](https://jira.lsstcorp.org/browse/DM-43011), which applies to the DP0.3 schemas, some measurements fields in the `apdb` schema were missing descriptions. These were filled in based on related fields. The errors in the DP0.3 schemas are being handled on the other ticket branch.

DM-43026: Add missing descriptions for SSSource measurement fields in apdb schema

---

yml/obsloctap.yaml

per agreement - the schema for obsplan is put in sdm_schema

DM-38824: use string not char so Postgress DDL is not char(1)

---

yml/dp02_dc2.yaml

Adding this annotation results in the following DDL:
```
CONSTRAINT "FSDO_DO" FOREIGN KEY("diaObjectId") REFERENCES dp02_dc2_catalogs."DiaObject" ("diaObjectId")
```

DM-43013: Add FK annotation to DP0.2 for ForcedSourceOnDiaObject to DiaObject

---

yml/dp02_dc2.yaml

The principal and column index annotations were determined in a pair programming session with @gpdf.
UCD assignments were based on a combination of discussion with @gpdf, comparison to other schemas, and the descriptions of valid words from the [UCD 1.5 list](https://ivoa.net/documents/UCD1+/20230125/EN-UCDlist-1.5-20230125.pdf).

DM-43009: Annotate DP0.2 Visit and CcdVisit with principal, column indices, and UCDs

---

yml/apdb.yaml
yml/dp01_dc2.yaml
yml/dp02_dc2.yaml
yml/dp03_10yr.yaml
yml/dp03_1yr.yaml
yml/hsc.yaml
yml/imsim.yaml

This follows the IVOA standard for exponentiation defined here:
https://ivoa.net/documents/VOUnits/20231104/PR-VOUnits-1.1-20231104.html
Table 7 in "2.9  Mathematical expressions containing symbols" indicates that `**` should be used for "Raised to the power expr."

DM-42993: Replace usage of "^" for exponentiation in unit definitions with "**"

---

yml/apdb.yaml
yml/dp01_dc2.yaml

Used the following command to make this change:
```
sed -i -E '/fits:tunit|ivoa:unit/s/([^*])\*([^*])/\1.\2/g' yml/*.yaml
```
The only updated schemas were `apdb` and `dp01_dc2`.

DM-43015: Change asterisk to single dot to denote multiplication in unit fields

---

yml/dp02_dc2.yaml

There is a known bug in the Science Portal which occurs when a column has a `time.epoch` UCD and a null unit string. This represents a temporary fix until that issue is resolved in Firefly.

DM-43348: Remove UCDs for Visit.expMidpt and Visit.expMidpt in DP0.2 schema

---

yml/apdb.yaml
yml/dp01_dc2.yaml

This fixes a few units in the APDB and DP0.1 schemas that are invalid according to the VOUnit specification.

DM-43333: Fix remaining non-controversial VOUnit usage errors in sdm_schemas

---

yml/dp02_dc2.yaml
yml/imsim.yaml

A few columns in DP0.2 and imsim were missing the length field. There are MySQL type overrides that include the length but these are not propagated to Felis's internal type engine.
The DP0.2 lengths were copied from the `mysql:datatype` and verified against the values for the corresponding columns in the Qserv ingest files.
The imsim length was also taken from the `mysql:datatype` value.

DM-43748: Add missing length fields to a few columns

---

yml/apdb.yaml
yml/dp03_10yr.yaml
yml/dp03_1yr.yaml

Remove erroneous prepending spaces from a few column descriptions.
Fix a few schema descriptions that were using an unnecessary prepending `>` character that was adding an unwanted newline. Those descriptions can just be double-quoted instead.

Remove extraneous whitespace from a few description fields

---

yml/apdb.yaml

Columns which are primary keys by default have autioncrement=auto in sqlalchemy which for single-column PK enables autoincrement. This does no big harm for APDB schema but creates unnecessary sequences in postgres. To avoid those extra sequences I mark all integer PK columns as autoincrement=false.

DM-43097: Add autoincrement=false to some columns

---

yml/apdb.yaml
yml/dp01_dc2.yaml
yml/dp02_dc2.yaml
yml/dp03_10yr.yaml
yml/dp03_1yr.yaml
yml/hsc.yaml
yml/imsim.yaml

This removes the redundant `mysql:datatype` definitions from all schemas for numeric types, including the Felis types `double`, `float`, `int` and `long`. These correspond to `DOUBLE`, `FLOAT`, `INTEGER` and `BIGINT` in MySQL, respectively.
[This script](https://github.com/JeremyMcCormick/rubin_scripts/blob/b45558e21c4c16ba16506afa86eae389c7efd3c7/sdm_schemas/remove-redundant-numerics.awk) from @gpdf was used to perform the cleanup.
These changes should have no practical effect on any schema workflows, since the resultant SQL output for each datatype was the same (a criteria for making this change) and we do not currently generate any DDL for creating live MySQL databases from any these schemas.
@ctslater Made some suggestions for verifying these changes: …

DM-43716: Remove all redundant mysql:datatype type overrides for Felis numerics

---

yml/dp01_dc2.yaml
yml/dp02_dc2.yaml
yml/hsc.yaml
yml/imsim.yaml

This removes all redundant `mysql:datatype: BOOLEAN` overrides from the schema files.

DM-43958: Remove redundant boolean datatype overrides

---

.github/workflows/build.yaml
.github/workflows/validate.yaml
tap-schema/build

This is an update to the TAP_SCHEMA workflow based on changes to Felis in [DM-42935](https://rubinobs.atlassian.net/browse/DM-42935), which will need to be merged first before the checks will pass.
The `build` script is updated to use the `tap-schema-index` command line argument instead of modifying the YAML files.
The Git workflows have also been changed to install Felis from `main` rather than the latest version on PyPI.
[DM-42935]: https://rubinobs.atlassian.net/browse/DM-42935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DM-42935: Set the schema index using Felis command line argument

---

yml/apdb.yaml
yml/dp01_dc2.yaml
yml/dp02_dc2.yaml
yml/dp03_10yr.yaml
yml/dp03_1yr.yaml
yml/hsc.yaml
yml/imsim.yaml

Removed all overrides from schemas for fixed length strings, similar to `mysql:datatype: CHAR(32)`. 
In all cases, there was an identical type definition of `char` or `string` on the column with the same length.

DM-43956: Remove all redundant overrides of fixed length strings

---

yml/apdb.yaml

Change `"0"` to `0` in `value` fields so that they have the correct type for the column.

DM-43998: Fix default values in apdb to use the correct datatype

---

yml/dp02_obscore.yaml
yml/imsim.yaml
yml/obsloctap.yaml
yml/oga_live_obscore.yaml

A pending update to Felis will change the validation of schemas to no longer accept columns with sized types that are missing a length. All such columns were updated to include explicit length values where they were missing.
Some columns, primarily in the `ObsCore` schemas, had an existing `votable:arraysize` that was changed to a `length`. This value will be used automatically for the `arraysize` when generating the TAP_SCHEMA, so they should be equivalent.
A few columns were changed from a sized string type to `text` where the VOTable type had been specified already as `clob`.
----
This PR should be merged before https://github.com/lsst/felis/pull/66.

DM-43946: Fix lengths and datatypes of string columns, primarily in ObsCore schemas

---

yml/imsim.yaml

The docstring for `DiaSource.ext_trailedSources_Naive_flag_edge` has been updated to reflect that it only indicates whether or not a trailed source's endpoints contain edge pixels. Other flags pertaining to trailed sources will not be persisted at this time and are only used for filtering purposes in `filterDiaSourceCatalog.py` in `ap_association`.

DM-41063: Update docstring for DiaSource.ext_trailedSources_Naive_flag_edge

---

yml/apdb.yaml
yml/dp02_dc2.yaml
yml/hsc.yaml
yml/imsim.yaml

Removed length fields from timestamp columns to cleanup warning messages. 
These were unused anyways, since Felis does not consider this a sized type and would not use the argument when constructing the SQLAlchemy objects.
A few lengths were also removed from `text` columns in APDB, since Felis doesn't accept a length for this type any longer. My understanding is that since APDB does its own type handling for Cassandra, this should be an inconsequential change.

DM-44059: Remove length fields from timestamp columns

---

yml/apdb.yaml
yml/dp03_10yr.yaml
yml/dp03_1yr.yaml

APDB changes were confirmed with @andy-slac. No MySQL datatype overrides are needed at all for this schema.
The overrides were removed from the DP0.3 schemas based on them being deployed in Postgres and not MySQL.

DM-44637: Remove unnecessary MySQL datatype overrides for string types

---

yml/apdb.yaml

There was one remaining column with a MySQL type override in the APDB schema:
```
- name: lcPeriodic
"@id": "#SSObject.lcPeriodic"
datatype: binary
length: 768
description: Periodic light curve features computed on phase/distance-corrected magnitudes (H), 6x32 floats.
mysql:datatype: BLOB(768)
```
I don't believe this is necessary, because APDB does not use MySQL.

Remove last mysql type override from APDB

---

yml/cdb_latiss.yaml
yml/cdb_lsstcomcam.yaml
yml/cdb_lsstcomcamsim.yaml

Very small amount of clean up for eff_time-related entries.

Update eff_time metric documentation

---

yml/cdb_latiss.yaml
yml/cdb_lsstcomcam.yaml
yml/cdb_lsstcomcamsim.yaml

Updated descriptions for the eff_time_*_scale metrics. Note that it appears that there was a typo (an extra `_psf`) in the naming of `eff_time_sky_bg_scale` and `eff_time_zero_point_scale` for `ccdvisit1_quicklook`. This typo was only in the name and not in the `@id`. See #231 for background information.

Updating eff_time_*_scale metrics

---

yml/dp03_1yr.yaml

Set precision=6 on three timestamp columns to match DP0.3 10yr

DM-44825: Add missing precision values on timestamps for DP0.3 1yr

---

yml/dp02_dc2.yaml

Fix portal bug with short not being handled correctly by Firefly plotting interface. It does not recognize short as a plottable data type.

Temporarily change MatchesTruth.truth_type to an int from short

---

tap-schema/build
tap-schema/sql/0000_tap_schema11.sql

**Summary**
Add size value to the TAP_SCHEMA column entries that get inserted. This addresses the issue where validators expect the "size" column to match the "arraysize" col.
The second change is to modify the engine-url to "mysql", as the TAP_SCHEMA  database currently deployed is in MySQL, so the insert statements need to be produced for that as far as I can see. I noticed this after trying to add values for the size column, which produced invalid SQL statements.
**How was this tested**
- Tested on data-dev, using a custom Docker image built locally.
- Test run using stilts taplint

DM-44878: Change build engine to mysql and set values for size on TAP_SCHEMA columns

---

yml/cdb_latiss.yaml
yml/cdb_lsstcomcam.yaml
yml/cdb_lsstcomcamsim.yaml

Prepend table names to FK constraint names so that they are unique within the schema.

DM-45623: Make foreign key constraint names unique in cdb schemas

---

tap-schema/build-all

Matches the current state of Qserv.
Preliminary to removing DP0.1 altogether.

DM-44884: Remove DP0.1 tables from TAP_SCHEMA on idfint and idfdev

---

.gitignore
scripts/test/create-databases.sh
yml/dp02_dc2.yaml

This fixes errors with foreign key constraints when creating the database for the DP0.2 schema.
The `--ignore-constraints` flag was removed from the database creation script used in the Github workflows.

DM-43115: Add missing primary keys to DP0.2 schema

---

yml/cdb_latiss.yaml
yml/cdb_lsstcomcam.yaml
yml/cdb_lsstcomcamsim.yaml

Adding magnitude limit columns to latiss, lsstcomcam, and lsstcomcamsim. The suggested name is "stats_mag_lim" to disambiguate from future magnitude limit values that could be derived from the catalogs or measurements of the image variance.

DM-45573: Add magnitude limit from exposure summary stats

---

browser/cdb_latiss.md
browser/cdb_lsstcomcam.md
browser/cdb_lsstcomcamsim.md
browser/cdb_startrackerfast.md
browser/cdb_startrackernarrow.md
browser/cdb_startrackerwide.md

I added new markdown files to the schema browser for missing ConsDB schemas (`cdb_latiss` and `cdb_startracker*`), and I also updated the schema titles in the sidebar so they are shorter and more concise.

DM-46895: Add missing ConsDB schemas

---

.github/workflows/docs.yaml
Makefile
_config.yml
browser/_layouts/schema.html
browser/_layouts/schema_index.html
browser/_sass/style2.scss
browser/dp01.md

Adds the following improvements and features to the schema browser:
- Sorts tables initially on Index and then Column Name if Index is not present
- Added additional columns to the table: Index, UCD, and Principal
- Column sorting (by clicking on the column header)
- Table contents search by text string using a search box
- Table pagination with selectable number of rows to display
- Export to CSV by clicking a button at the top of each table
Advanced table features were enabled by the well-known [DataTables](https://datatables.net/) Javascript library and its script dependencies.
Also included several miscellaneous fixes:
- Changed the "Updated" date to use the site upload date rather than `last_modified` (Otherwise, this only updates when the HTML pages themselves are changed, which …

DM-41867: Add improvements to schema browser

---

browser/_layouts/schema.html
browser/_sass/style2.scss

This adds a checkbox for toggling table pagination, which is turned off by default.
Column anchor links are restored, too, and some minor changes were made to the stylesheet so that the page content fits in the viewport, eliminating the extra vertical scrollbar.

DM-46982: Add toggle for table pagination

---

SConstruct
ups/eupspkg.cfg.sh
ups/sdm_schemas.table

This adds `lsst.sdm_schemas` to the `PYTHONPATH` so that schemas are available using a resource path.

DM-47069: Add EUPS config to sdm_schemas for resource path support

---

python/lsst/sdm_schemas/schemas/imsim.yaml

This was inadvertently merged and needs to be reverted as it breaks `ci_imsim`.

Revert addition of extendedness column to imsim

---

.github/workflows/build.yaml
.gitignore
python/lsst/sdm_schemas/schemas/imsim.yaml
tap-schema/build

Fix issues in the build workflow:
1. Use the standard workflow trigger instead of `on: push`
2. Add `fetch-depth: 0` to checkout
3. Build and push Docker images on all triggers, including for user branches and merges to `main`
4. Update the `tap-schema/build` script so it creates Docker images with the proper names for all cases (tags, branches & PRs)
Miscellaneous changes:
1. Remove a commented-out column from `imsim`
2. Add lsst versions file and `config.log` to `.gitignore`

DM-47403: Fix problems in GitHub build workflow

---

python/lsst/sdm_schemas/schemas/cdb_latiss.yaml
python/lsst/sdm_schemas/schemas/cdb_lsstcomcam.yaml

Move data added by Elana including mount jitter to exposure_quicklook instead of exposure tables.

Move mount, jitter, to exposure_quicklook

---

python/lsst/sdm_schemas/schemas/hsc.yaml
python/lsst/sdm_schemas/schemas/imsim.yaml

This flag no longer has any meaning in the new pipeline flow, as the step it represented was removed.

DM-46991: Drop calib_detected from Source schemas.

---

.github/workflows/compare.yaml
python/lsst/sdm_schemas/schemas/deployed-schemas.txt

This PR adds a workflow that will check for changes in schemas using the `felis diff` command. One comparison is performed using the `deepdiff` comparator, which will show all changes, including ones to metadata fields, e.g., `ivoa_ucd`. Another comparison step will use `alembic`, which will only show updates that affect the relational data model.
Finally, a comparison using the `alembic` mode will be performed on each schema from a list of "deployed" schema YAML files (which is also added by this PR). An error will be raised if any of them have changed (`dp02_dc2`, etc.).
A preliminary step in the workflow uses `git diff` to detect which files were changed. Files which were not changed in the repository need not be checked.
----
~~Blocked by https://github.com/lsst/felis/pull/109~~
This …

DM-46158: Add workflow to perform schema comparisons and check for changes to deployed schemas

---

.github/pull_request_template.md

Prepend links in PR template with `/lsst/sdm_schemas/blob/main` so that they work correctly.

Fix links in PR template

---

python/lsst/sdm_schemas/schemas/dp02_dc2.yaml

Also remove unnecessary and incorrect arraysize override.

DM-43996: Add desired column order to CoaddPatches

---

CONTRIBUTING.md
docs/DRP.md

DM-48178: Add documentation for DRP schemas.

---

python/lsst/sdm_schemas/schemas/hsc.yaml
python/lsst/sdm_schemas/schemas/imsim.yaml

DM-48591: Add multiprofit two-Gaussian PSF and Sersic columns

---

tap-schema/build
tap-schema/build-all

This PR adds support for building a TAP_SCHEMA Docker image containing ConsDB schemas. The environment is called `usdf-dev-cdb` and intended for deployment on `usdf-rsp-dev`. 
A new feature in Felis was used to ensure that the `key_id` values for the `keys` and `key_columns` tables are unique by prepending the name of the schema to them. (This feature is activated only when building the ConsDB environment.)
Merge after https://github.com/lsst/felis/pull/136 which adds the new Felis feature.

DM-43728: Build TAP_SCHEMA Docker images for ConsDB

---

.github/workflows/compare.yaml

This PR updates the `compare` workflow to make sure that the old and new versions of the schema exist before running the `diff` commands.

Fix compare workflow

---

tap-schema/build-all

This PR adds a `usdf-prod-cdb` image for ConsDB, intended for use on `usdf-rsp` and `usdf-rsp-int`.

DM-43728: Build usdf-prod-cdb image

---

python/lsst/sdm/schemas/cdb_lsstcam.yaml

This PR adds a schema for LSSTCam in the consolidated database. The schema is a direct copy of LSSTComCam for now, but divergence should be expected down the road.

DM-49406 Add a CDB schema for LSSTCam

---

docs/changes/DM-49767.sci.md
tap-schema/sql/0000_tap_schema11.sql

Upstream CADC repo for the TAP service has renamed the field id in table columns of TAP_SCHEMA to column_id
https://github.com/opencadc/tap/commit/5cc177da7e9b00e4a2a46d74e77312911551e92c
Note: This may require some coordination since it's a backwards incompatible change (TAP needs updated version to match field name)

DM-49767: Change id to column_id in tap_schema columns

---

.github/actions/setup-python/action.yaml
.github/workflows/check_band_columns.yaml
python/lsst/sdm/schemas/apdb.yaml
python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

This PR adds a workflow for checking the consistency of band column definitions in the following schemas:
- dp02_dc2
- dp03*
- imsim
- hsc
- apdb
Several inconsistencies in a few of these schemas were fixed, so the check currently passes.
Introduction of any inconsistencies between band column definitions will cause the workflow and PR status check to fail.
----
~~The tools for checking the band columns are introduced by [this PR in sdm_tools](https://github.com/lsst/sdm_tools/pull/4), which needs to be merged before this one.~~
~~This PR will also need to be updated to use the `main` branch of sdm_tools in `requirements.txt` instead of a ticket branch.~~

DM-48803: Add workflow for checking consistency of band columns

---

docs/changes/DM-50252.sci.md
tap-schema/sql/0000_tap_schema11.sql

Note: This reapplies previous changes that were reverted from https://github.com/lsst/sdm_schemas/pull/326
Upstream CADC repo for the TAP service has renamed the field id in table columns of TAP_SCHEMA to column_id
https://github.com/opencadc/tap/commit/5cc177da7e9b00e4a2a46d74e77312911551e92c
Note: This may require some coordination since it's a backwards incompatible change (TAP needs updated version to match field name)

Added api_created column to the tap_schema tables table and changed id to column_id for columns table

---

tap-schema/build

Merge after https://github.com/lsst/felis/pull/144
Dependence on Felis development branch also needs to be dropped from `requirements.txt`.

DM-50914: Use '--force-unbound-arraysize' flag when generating TAP_SCHEMA SQL output

---

docs/changes/DM-51478.dr.md
python/lsst/sdm/schemas/dp02_dc2.yaml
python/lsst/sdm/schemas/dp02_obscore.yaml

This change is suitable for deployment both to data-int and to data (prod).  On data-int it will be followed by a separate PR replacing the dp02_obscore.yaml file with a new ivoa_obscore.yaml file for DP1 (and beyond).

DM-51478: Copy DP0.2's ObsCore table schema from ivoa.ObsCore to dp02_dc2_catalogs.ObsCore 

---

docs/changes/DM-51411.dr.md
python/lsst/sdm/schemas/dp1.yaml

DM-51411: Change 'fits:tunit' to 'ivoa:unit' in DP1 schema

---

docs/changes/DM-51506.dr.md
python/lsst/sdm/schemas/dp1.yaml

No longer needed, due to Felis improvements

DM-51506: Remove arraysize overrides from DP1 static ObsCore table

---

docs/changes/DM-51549.dr.md
python/lsst/sdm/schemas/ivoa_obscore.yaml

Follows recent dax_obscore change that removed the need for the static addition of the obs_title column that was done in DP0.2
Also corrects length of `obs_publisher_did` to match Qserv column

DM-51549: Add obs_title to `ivoa.ObsCore`

---

tap-schema/build-all

Patch to sync the `idfint` and `idfdev` environments (should have be done in #373).

DM-51511: Copy idfint environment to idfdev

---

tap-schema/build-all

Full order on all IDF Qserv-TAP instances is now DP1, ivoa, DP0.2

DM-51511 (patch): Rotate schema_index order to put DP1 first

---

python/lsst/sdm/schemas/hsc.yaml
python/lsst/sdm/schemas/imsim.yaml

DM-47738: Add deblend_depth to object table

---

docs/changes/DM-51552.dr.md
python/lsst/sdm/schemas/dp1.yaml

~~This is branched off of #364 so should be merged after that PR.~~
I did not change the schema version yet.

DM-51552: Add "visit+detector" foreign key relationships to DP1 schema

---

Makefile

Update the `Makefile` to validate the schemas before generating the site (doesn't effect CI where validation runs as a separate job).

Validate the schemas before generating the site
